#!/usr/bin/env bash
# repos-check.sh: which onboarded repos are behind the rules as they stand.
#
# The check `make upgrade` runs at step 7, available at the other moment it
# matters — after a rule is edited. What is asserted here is mostly the exit
# codes: a post-commit hook and a Makefile target both branch on them, and a
# check that reported drift in prose while exiting 0 would be read by neither.
#
# XDG_CONFIG_HOME is pointed inside the sandbox for the same reason
# test-repo-registry.sh does it: the real registry names the developer's own
# repos, and a test that read it would assert against whatever happens to be
# rendered on the machine running it.
#
# Every case passes --registry-only. The scan half walks $HOME (isolated by
# tests/lib.sh, so it would find nothing here anyway) and is already covered by
# test-registry-scan.sh; what this file is about is the report and its codes.
# shellcheck source=tests/lib.sh
. "$(cd "$(dirname "$0")" && pwd)/lib.sh"
setup_sandbox

export XDG_CONFIG_HOME="${SANDBOX}/config-home"
REGISTRY="${XDG_CONFIG_HOME}/second-brain-workflow/repos"
mkdir -p "$(dirname "${REGISTRY}")"

# Isolated from ${ENGINE}/rules like test-render.sh and test-repo-registry.sh:
# those are personal content on a real machine and absent in the public repo.
RULES_FIXTURES="${FIXTURES}/rules"
render() { "${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "$@"; }
CHECK="${ENGINE}/scripts/repos-check.sh"

OUT="${SANDBOX}/out"
RC=0
run_check() {
  RC=0
  SBW_RULES_DIR="${RULES_FIXTURES}" "${CHECK}" --registry-only >"${OUT}" 2>&1 || RC=$?
}
out_has() {
  TESTS_RUN=$((TESTS_RUN + 1))
  if grep -qF -- "$1" "${OUT}"; then pass "$2"; else fail "$2" "$(cat "${OUT}")"; fi
}
out_lacks() {
  TESTS_RUN=$((TESTS_RUN + 1))
  if grep -qF -- "$1" "${OUT}"; then fail "$2" "$(cat "${OUT}")"; else pass "$2"; fi
}
rc_is() {
  TESTS_RUN=$((TESTS_RUN + 1))
  if [ "${RC}" = "$1" ]; then pass "$2"; else fail "$2" "exit ${RC}, want $1: $(cat "${OUT}")"; fi
}
real() { (cd "$1" && pwd -P); }

echo "repos-check"

# --- a machine with nothing onboarded ---------------------------------------
# The state every fresh install is in. It must not read as a finding, and it
# must not claim anything about repos it never looked for.
run_check
rc_is 0 "an empty registry is not a finding"
out_has "the registry names none" "and says so rather than counting to zero"
out_has "registered repos only" "and names the question it answered"

# --- a rendered repo, up to date --------------------------------------------
REPO="${SANDBOX}/repo"
make_target_repo "${REPO}"
render "${REPO}" >/dev/null 2>&1
printf '%s\n' "$(real "${REPO}")" > "${REGISTRY}"

run_check
rc_is 0 "a repo matching the current rules exits clean"
out_has "up to date: $(real "${REPO}")" "and is named as up to date"

# --- the same repo, one rendered file edited --------------------------------
# The drift a rule edit produces, injected from the other side: the point is
# that --check disagrees, not how it came to. Found by its provenance marker
# rather than named: a file the render did not write is hand-written as far as
# render.py is concerned, and editing one produces no drift at all — which is
# how this case first passed while testing nothing.
DRIFTED="$(grep -rlF 'generated by second-brain-workflow@' "${REPO}/.cursor/rules" | head -1)"
[ -n "${DRIFTED}" ] || { fail "no rendered file to drift" "$(ls -R "${REPO}")"; finish; }
printf '\n- injected drift\n' >> "${DRIFTED}"

run_check
rc_is 1 "drift exits 1, so a hook or a Makefile target can branch on it"
out_has "DRIFT $(real "${REPO}")" "and the repo is named"
out_has "fix: ${ENGINE}/scripts/render.py $(real "${REPO}")" "with the command that fixes it"
out_has "This script does not render" "and it states that it did not render"

# Nothing is repaired by looking: the whole contract is report-only.
TESTS_RUN=$((TESTS_RUN + 1))
if grep -qF 'injected drift' "${DRIFTED}"; then
  pass "the drifted file is left exactly as it was"
else
  fail "the drifted file is left exactly as it was" "repos-check.sh wrote to the target"
fi

# --- the mode travels with the verdict --------------------------------------
# The report is where the reader meets the `fix:` command, and for three releases
# it could not say whether running that command would keep a repo's rendered
# files out of its remote. render.py preserves the mode now; this is what lets a
# reader see that it does.
out_has "[shared]" "a shared repo's verdict carries its mode"

# Re-rendered with --local (which clears the drift), then drifted again, because
# the mode hint only belongs on a line that hands the reader a command.
render "${REPO}" --local >/dev/null 2>&1
printf '%s\tmode=local\n' "$(real "${REPO}")" > "${REGISTRY}"
DRIFTED="$(grep -rlF 'generated by second-brain-workflow@' "${REPO}/.cursor/rules" | head -1)"
printf '\n- injected drift\n' >> "${DRIFTED}"
run_check
rc_is 1 "a local repo with drift still exits 1"
out_has "[local]" "a local repo's verdict carries its mode"
out_has "stays local" "and the fix line says the command preserves it"

# A repo the scan finds and the registry does not name has no recorded mode and
# no block to infer one from. `unknown` is the honest label — and the report says
# the next render settles it, rather than implying a decision nobody made.
UNKNOWN_ROOT="${SANDBOX}/unknown-root"
UNKNOWN_REPO="${UNKNOWN_ROOT}/unknown-mode"
make_target_repo "${UNKNOWN_REPO}"
render "${UNKNOWN_REPO}" --no-register >/dev/null 2>&1
: > "${REGISTRY}"
RC=0
SBW_RULES_DIR="${RULES_FIXTURES}" SBW_SCAN_ROOTS="$(real "${UNKNOWN_ROOT}")" SBW_SCAN_DEPTH=5 \
  "${CHECK}" >"${OUT}" 2>&1 || RC=$?
out_has "[unknown]" "a repo with no recorded mode and no block reads as unknown"

printf '%s\n' "$(real "${REPO}")" > "${REGISTRY}"

# --- a registered path that is gone -----------------------------------------
# The failure mode this whole family exists to refuse: an unanswerable question
# must never come back as "all up to date".
rm -rf "${REPO}"
run_check
rc_is 0 "an unreachable path is a warning, not drift"
out_has "registered, but not there" "and it is named"
out_lacks "up to date" "and nothing is claimed to be current"

# --- a repo whose rule files resolve to nothing ------------------------------
# The one case that needs the scan, so it does not use run_check. Not drift: the
# repo carries no readable rendered output at all, so it is in neither source
# and appears in none of the counts above — which is exactly how it went
# unreported. `all N up to date` was true of the repos that were checkable and
# read, on the machine this came from, as a clean bill of health.
: > "${REGISTRY}"
BROKEN_ROOT="${SANDBOX}/scan-root"
BROKEN_REPO="${BROKEN_ROOT}/repo-dangling"
mkdir -p "${BROKEN_REPO}/.cursor/rules"
ln -s "${SANDBOX}/gone/frontend-angular.mdc" \
  "${BROKEN_REPO}/.cursor/rules/frontend-angular.mdc"

RC=0
SBW_RULES_DIR="${RULES_FIXTURES}" SBW_SCAN_ROOTS="$(real "${BROKEN_ROOT}")" SBW_SCAN_DEPTH=5 \
  "${CHECK}" >"${OUT}" 2>&1 || RC=$?
rc_is 1 "a repo loading no rules exits 1, like drift — both mean a repo is not ruled"
out_has "BROKEN rule files resolve to nothing: $(real "${BROKEN_REPO}")" \
  "and the repo is named"
out_has "or delete the dangling links, if that repo is abandoned." \
  "with both repairs offered, since the script cannot know which was meant"
out_has "They are in no count on this line" \
  "and the summary says the broken repos are outside its counts"

# --registry-only promises an answer about registered repos alone. A finding
# about a repo that is by definition unregistered would be that promise broken,
# and the flag exists for callers who need the narrower question answered.
RC=0
SBW_RULES_DIR="${RULES_FIXTURES}" SBW_SCAN_ROOTS="$(real "${BROKEN_ROOT}")" SBW_SCAN_DEPTH=5 \
  "${CHECK}" --registry-only >"${OUT}" 2>&1 || RC=$?
out_lacks "BROKEN" "--registry-only does not report it, having promised not to look"
rc_is 0 "and stays clean, because the question it answered had no findings"

# --- an unknown option ------------------------------------------------------
RC=0
"${CHECK}" --nonsense >"${OUT}" 2>&1 || RC=$?
rc_is 2 "an unknown option exits 2 rather than checking something else"

finish
