#!/usr/bin/env bash
# repos-check.sh: which onboarded repos are behind the rules as they stand.
#
# The check `make upgrade` runs at step 7, available at the other moment it
# matters — after a rule is edited. What is asserted here is mostly the exit
# codes: a post-commit hook and a Makefile target both branch on them, and a
# check that reported drift in prose while exiting 0 would be read by neither.
#
# XDG_CONFIG_HOME is pointed inside the sandbox for the same reason
# test-repo-registry.sh does it: the real registry names the developer's own
# repos, and a test that read it would assert against whatever happens to be
# rendered on the machine running it.
#
# Every case passes --registry-only. The scan half walks $HOME (isolated by
# tests/lib.sh, so it would find nothing here anyway) and is already covered by
# test-registry-scan.sh; what this file is about is the report and its codes.
# shellcheck source=tests/lib.sh
. "$(cd "$(dirname "$0")" && pwd)/lib.sh"
setup_sandbox

export XDG_CONFIG_HOME="${SANDBOX}/config-home"
REGISTRY="${XDG_CONFIG_HOME}/second-brain-workflow/repos"
mkdir -p "$(dirname "${REGISTRY}")"

# Isolated from ${ENGINE}/rules like test-render.sh and test-repo-registry.sh:
# those are personal content on a real machine and absent in the public repo.
RULES_FIXTURES="${FIXTURES}/rules"
render() { "${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "$@"; }
CHECK="${ENGINE}/scripts/repos-check.sh"

OUT="${SANDBOX}/out"
RC=0
run_check() {
  RC=0
  SBW_RULES_DIR="${RULES_FIXTURES}" "${CHECK}" --registry-only >"${OUT}" 2>&1 || RC=$?
}
out_has() {
  TESTS_RUN=$((TESTS_RUN + 1))
  if grep -qF -- "$1" "${OUT}"; then pass "$2"; else fail "$2" "$(cat "${OUT}")"; fi
}
out_lacks() {
  TESTS_RUN=$((TESTS_RUN + 1))
  if grep -qF -- "$1" "${OUT}"; then fail "$2" "$(cat "${OUT}")"; else pass "$2"; fi
}
rc_is() {
  TESTS_RUN=$((TESTS_RUN + 1))
  if [ "${RC}" = "$1" ]; then pass "$2"; else fail "$2" "exit ${RC}, want $1: $(cat "${OUT}")"; fi
}
real() { (cd "$1" && pwd -P); }

echo "repos-check"

# --- a machine with nothing onboarded ---------------------------------------
# The state every fresh install is in. It must not read as a finding, and it
# must not claim anything about repos it never looked for.
run_check
rc_is 0 "an empty registry is not a finding"
out_has "the registry names none" "and says so rather than counting to zero"
out_has "registered repos only" "and names the question it answered"

# --- a rendered repo, up to date --------------------------------------------
REPO="${SANDBOX}/repo"
make_target_repo "${REPO}"
render "${REPO}" >/dev/null 2>&1
printf '%s\n' "$(real "${REPO}")" > "${REGISTRY}"

run_check
rc_is 0 "a repo matching the current rules exits clean"
out_has "up to date: $(real "${REPO}")" "and is named as up to date"

# --- the same repo, one rendered file edited --------------------------------
# The drift a rule edit produces, injected from the other side: the point is
# that --check disagrees, not how it came to. Found by its provenance marker
# rather than named: a file the render did not write is hand-written as far as
# render.py is concerned, and editing one produces no drift at all — which is
# how this case first passed while testing nothing.
DRIFTED="$(grep -rlF 'generated by second-brain-workflow@' "${REPO}/.cursor/rules" | head -1)"
[ -n "${DRIFTED}" ] || { fail "no rendered file to drift" "$(ls -R "${REPO}")"; finish; }
printf '\n- injected drift\n' >> "${DRIFTED}"

run_check
rc_is 1 "drift exits 1, so a hook or a Makefile target can branch on it"
out_has "DRIFT $(real "${REPO}")" "and the repo is named"
out_has "fix: ${ENGINE}/scripts/render.py $(real "${REPO}")" "with the command that fixes it"
out_has "This script does not render" "and it states that it did not render"

# Nothing is repaired by looking: the whole contract is report-only.
TESTS_RUN=$((TESTS_RUN + 1))
if grep -qF 'injected drift' "${DRIFTED}"; then
  pass "the drifted file is left exactly as it was"
else
  fail "the drifted file is left exactly as it was" "repos-check.sh wrote to the target"
fi

# --- a registered path that is gone -----------------------------------------
# The failure mode this whole family exists to refuse: an unanswerable question
# must never come back as "all up to date".
rm -rf "${REPO}"
run_check
rc_is 0 "an unreachable path is a warning, not drift"
out_has "registered, but not there" "and it is named"
out_lacks "up to date" "and nothing is claimed to be current"

# --- an unknown option ------------------------------------------------------
RC=0
"${CHECK}" --nonsense >"${OUT}" 2>&1 || RC=$?
rc_is 2 "an unknown option exits 2 rather than checking something else"

finish
