#!/usr/bin/env bash
# render.py: output shape per target, idempotency, drift, pruning, and the
# rules that protect a user's own files.
# shellcheck source=tests/lib.sh
. "$(cd "$(dirname "$0")" && pwd)/lib.sh"
setup_sandbox

# Isolated from ${ENGINE}/rules and ${ENGINE}/AGENTS.md — those may be
# personal content in a real checkout (or absent entirely in the public
# engine repo). render() always points at fixture rules instead.
RULES_FIXTURES="${FIXTURES}/rules"
render() { "${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "$@"; }
REPO="${SANDBOX}/repo"
make_target_repo "${REPO}"

echo "render.py"

# --- all targets ------------------------------------------------------------
render "${REPO}" >/dev/null 2>&1
assert_exit 0 $? "renders all targets"
assert_file "${REPO}/.cursor/rules/frontend-angular.mdc" "cursor: .mdc written"
assert_file "${REPO}/.claude/rules/frontend-angular.md"  "claude-code: rule written"
assert_file "${REPO}/CLAUDE.md"                          "claude-code: CLAUDE.md written"
assert_file "${REPO}/AGENTS.md"                          "agents: AGENTS.md written"

assert_file "${REPO}/.cursor/rules/local-only.mdc" "hand-written rule survives"

# --- format correctness -----------------------------------------------------
assert_contains "${REPO}/.cursor/rules/frontend-angular.mdc" 'globs:' \
  "cursor rule keeps native globs"
assert_contains "${REPO}/.claude/rules/frontend-angular.md" 'paths:' \
  "claude rule uses native paths:"
assert_contains "${REPO}/.claude/rules/frontend-angular.md" '"\*\*/\*.component.ts"' \
  "claude paths: is a yaml list of globs"
assert_contains "${REPO}/CLAUDE.md" '@AGENTS.md' \
  "CLAUDE.md imports AGENTS.md rather than forking it"

# Frontmatter must start on line 1 or the agent cannot parse it.
TESTS_RUN=$((TESTS_RUN + 1))
if [ "$(head -n 1 "${REPO}/.cursor/rules/frontend-angular.mdc")" = "---" ]; then
  pass "provenance header does not displace frontmatter"
else
  fail "provenance header does not displace frontmatter"
fi

assert_contains "${REPO}/.cursor/rules/frontend-angular.mdc" 'generated by second-brain-workflow@' \
  "rendered file carries provenance"

# --- idempotency and drift --------------------------------------------------
out="$(render "${REPO}" 2>&1)"
TESTS_RUN=$((TESTS_RUN + 1))
if echo "${out}" | grep -q "Rendered 0 file(s)"; then
  pass "second run is a no-op"
else
  fail "second run is a no-op" "${out}"
fi

render "${REPO}" --check >/dev/null 2>&1
assert_exit 0 $? "--check clean after render"

echo "tampered" >> "${REPO}/.claude/rules/frontend-angular.md"
render "${REPO}" --check >/dev/null 2>&1
assert_exit 1 $? "--check exits 1 on drift"

render "${REPO}" >/dev/null 2>&1
render "${REPO}" --check >/dev/null 2>&1
assert_exit 0 $? "--check clean again after re-render"

# --- dry run writes nothing -------------------------------------------------
rm -f "${REPO}/.cursor/rules/frontend-angular.mdc"
render "${REPO}" --dry-run >/dev/null 2>&1
assert_no_file "${REPO}/.cursor/rules/frontend-angular.mdc" "--dry-run writes nothing"
render "${REPO}" >/dev/null 2>&1

# --- hand-written CLAUDE.md is never clobbered ------------------------------
printf '# Mine\n\nHand written.\n' > "${REPO}/CLAUDE.md"
render "${REPO}" >/dev/null 2>&1
assert_contains "${REPO}/CLAUDE.md" 'Hand written' "hand-written CLAUDE.md survives"
assert_not_contains "${REPO}/CLAUDE.md" '@AGENTS.md' "hand-written CLAUDE.md not rewritten"
rm -f "${REPO}/CLAUDE.md"
render "${REPO}" >/dev/null 2>&1

# --- legacy symlinks from the pre-copy layout -------------------------------
rm -f "${REPO}/.cursor/rules/frontend-angular.mdc"
ln -sfn "${RULES_FIXTURES}/frontend-angular.md" "${REPO}/.cursor/rules/frontend-angular.mdc"
render "${REPO}" --check >/dev/null 2>&1
assert_exit 1 $? "legacy symlink reported as drift"
render "${REPO}" >/dev/null 2>&1
TESTS_RUN=$((TESTS_RUN + 1))
if [ -f "${REPO}/.cursor/rules/frontend-angular.mdc" ] && \
   [ ! -L "${REPO}/.cursor/rules/frontend-angular.mdc" ]; then
  pass "legacy symlink replaced by a real file"
else
  fail "legacy symlink replaced by a real file"
fi

# --- pruning ----------------------------------------------------------------
printf -- '---\ndescription: gone\n---\n\n<!-- generated by second-brain-workflow@old from rules/gone.md -->\nstale\n' \
  > "${REPO}/.cursor/rules/gone.mdc"
render "${REPO}" >/dev/null 2>&1
assert_no_file "${REPO}/.cursor/rules/gone.mdc" "stale generated rule pruned"
assert_file "${REPO}/.cursor/rules/local-only.mdc" "hand-written rule never pruned"

# One target must not prune another agent's files, or a repo shared with a
# colleague on the other editor gets gutted.
render "${REPO}" --targets cursor >/dev/null 2>&1
assert_file "${REPO}/.claude/rules/frontend-angular.md" \
  "single target leaves the other agent's files alone"

# --- scoping invariant ------------------------------------------------------
BAD="${RULES_FIXTURES}/zz-test-bad.md"
printf -- '---\n---\n\n- no paths, no description\n' > "${BAD}"
render --explain >/dev/null 2>&1
rc=$?
rm -f "${BAD}"
assert_exit 1 "${rc}" "rule with neither paths nor description is rejected"

# --- config -----------------------------------------------------------------
printf 'RENDER_TARGETS=cursor\n' > "${SANDBOX}/config"
REPO2="${SANDBOX}/repo2"
make_target_repo "${REPO2}"
SBW_CONFIG_FILE="${SANDBOX}/config" render "${REPO2}" >/dev/null 2>&1
assert_file   "${REPO2}/.cursor/rules/frontend-angular.mdc" "config file sets RENDER_TARGETS"
assert_no_file "${REPO2}/.claude/rules"                     "config file narrows targets"

REPO3="${SANDBOX}/repo3"
make_target_repo "${REPO3}"
SBW_CONFIG_FILE="${SANDBOX}/config" RENDER_TARGETS=agents render "${REPO3}" >/dev/null 2>&1
assert_file    "${REPO3}/AGENTS.md"    "env overrides config file"
assert_no_file "${REPO3}/.cursor/rules/frontend-angular.mdc" "env override is exclusive"

# --- glob validity ----------------------------------------------------------
# A pattern that silently matches nothing is worse than a broken one: the rule
# just never fires. Both agents fail this way, so it is caught at render time.
BAD2="${RULES_FIXTURES}/zz-test-badglob.md"
printf -- '---\npaths:\n  - "photos [2024/**"\ndescription: bad glob\n---\n\n- oops\n' > "${BAD2}"
render --explain >/dev/null 2>&1
rc=$?
rm -f "${BAD2}"
assert_exit 1 "${rc}" "unbalanced bracket in a glob is rejected"

# A brace group is now legal in the canonical paths: list and only fails where
# Cursor's comma-separated globs cannot carry it.
BAD3="${RULES_FIXTURES}/zz-test-braces.md"
printf -- '---\npaths:\n  - "src/**/*.{ts,tsx}"\ndescription: braces\n---\n\n- ok\n' > "${BAD3}"
render --explain --targets cursor >/dev/null 2>&1
rc_cursor=$?
render --explain --targets claude-code >/dev/null 2>&1
rc_claude=$?
rm -f "${BAD3}"
assert_exit 1 "${rc_cursor}" "brace group rejected when cursor is a target"
assert_exit 0 "${rc_claude}" "brace group allowed when only claude-code is a target"

# --- the adopter's first five minutes ----------------------------------------
# A clone with no conventions yet must render what it can and say what is
# missing, not traceback. This is the cold-start path, not an error state.
AGENTS_FIXTURE="${FIXTURES}/AGENTS.md"
AGENTS_BAK="${SANDBOX}/AGENTS.md.bak"
cp "${AGENTS_FIXTURE}" "${AGENTS_BAK}"
rm -f "${AGENTS_FIXTURE}"
REPO4="${SANDBOX}/repo4"
make_target_repo "${REPO4}"
out="$(render "${REPO4}" 2>&1)"
rc=$?
cp "${AGENTS_BAK}" "${AGENTS_FIXTURE}"
assert_exit 0 "${rc}" "missing AGENTS.md does not fail the render"
assert_file   "${REPO4}/.claude/rules/frontend-angular.md" "rules still render without AGENTS.md"
assert_no_file "${REPO4}/AGENTS.md"                        "AGENTS.md not fabricated"
assert_no_file "${REPO4}/CLAUDE.md"                        "CLAUDE.md skipped without its import target"
TESTS_RUN=$((TESTS_RUN + 1))
if echo "${out}" | grep -q "AGENTS.md.example"; then
  pass "says how to fix it"
else
  fail "says how to fix it" "${out}"
fi

finish
