#!/usr/bin/env bash
# render.py: output shape per target, idempotency, drift, pruning, and the
# rules that protect a user's own files.
# shellcheck source=tests/lib.sh
. "$(cd "$(dirname "$0")" && pwd)/lib.sh"
setup_sandbox

# Isolated from ${ENGINE}/rules and ${ENGINE}/AGENTS.md — those may be
# personal content in a real checkout (or absent entirely in the public
# engine repo). render() always points at fixture rules instead.
RULES_FIXTURES="${FIXTURES}/rules"
render() { "${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "$@"; }
REPO="${SANDBOX}/repo"
make_target_repo "${REPO}"

echo "render.py"

# --- all targets ------------------------------------------------------------
render "${REPO}" >/dev/null 2>&1
assert_exit 0 $? "renders all targets"
assert_file "${REPO}/.cursor/rules/frontend-angular.mdc" "cursor: .mdc written"
assert_file "${REPO}/.claude/rules/frontend-angular.md"  "claude-code: rule written"
assert_file "${REPO}/CLAUDE.md"                          "claude-code: CLAUDE.md written"
assert_file "${REPO}/AGENTS.md"                          "agents: AGENTS.md written"

assert_file "${REPO}/.cursor/rules/local-only.mdc" "hand-written rule survives"

# --- format correctness -----------------------------------------------------
assert_contains "${REPO}/.cursor/rules/frontend-angular.mdc" 'globs:' \
  "cursor rule keeps native globs"
assert_contains "${REPO}/.claude/rules/frontend-angular.md" 'paths:' \
  "claude rule uses native paths:"
assert_contains "${REPO}/.claude/rules/frontend-angular.md" '"\*\*/\*.component.ts"' \
  "claude paths: is a yaml list of globs"
assert_contains "${REPO}/CLAUDE.md" '@AGENTS.md' \
  "CLAUDE.md imports AGENTS.md rather than forking it"

# Frontmatter must start on line 1 or the agent cannot parse it.
TESTS_RUN=$((TESTS_RUN + 1))
if [ "$(head -n 1 "${REPO}/.cursor/rules/frontend-angular.mdc")" = "---" ]; then
  pass "provenance header does not displace frontmatter"
else
  fail "provenance header does not displace frontmatter"
fi

assert_contains "${REPO}/.cursor/rules/frontend-angular.mdc" 'generated by second-brain-workflow@' \
  "rendered file carries provenance"

# --- idempotency and drift --------------------------------------------------
out="$(render "${REPO}" 2>&1)"
TESTS_RUN=$((TESTS_RUN + 1))
if echo "${out}" | grep -q "Rendered 0 file(s)"; then
  pass "second run is a no-op"
else
  fail "second run is a no-op" "${out}"
fi

render "${REPO}" --check >/dev/null 2>&1
assert_exit 0 $? "--check clean after render"

echo "tampered" >> "${REPO}/.claude/rules/frontend-angular.md"
render "${REPO}" --check >/dev/null 2>&1
assert_exit 1 $? "--check exits 1 on drift"

render "${REPO}" >/dev/null 2>&1
render "${REPO}" --check >/dev/null 2>&1
assert_exit 0 $? "--check clean again after re-render"

# --- dry run writes nothing -------------------------------------------------
rm -f "${REPO}/.cursor/rules/frontend-angular.mdc"
render "${REPO}" --dry-run >/dev/null 2>&1
assert_no_file "${REPO}/.cursor/rules/frontend-angular.mdc" "--dry-run writes nothing"
render "${REPO}" >/dev/null 2>&1

# --- hand-written CLAUDE.md is never clobbered ------------------------------
printf '# Mine\n\nHand written.\n' > "${REPO}/CLAUDE.md"
render "${REPO}" >/dev/null 2>&1
assert_contains "${REPO}/CLAUDE.md" 'Hand written' "hand-written CLAUDE.md survives"
assert_not_contains "${REPO}/CLAUDE.md" '@AGENTS.md' "hand-written CLAUDE.md not rewritten"
rm -f "${REPO}/CLAUDE.md"
render "${REPO}" >/dev/null 2>&1

# --- legacy symlinks from the pre-copy layout -------------------------------
rm -f "${REPO}/.cursor/rules/frontend-angular.mdc"
ln -sfn "${RULES_FIXTURES}/frontend-angular.md" "${REPO}/.cursor/rules/frontend-angular.mdc"
render "${REPO}" --check >/dev/null 2>&1
assert_exit 1 $? "legacy symlink reported as drift"
render "${REPO}" >/dev/null 2>&1
TESTS_RUN=$((TESTS_RUN + 1))
if [ -f "${REPO}/.cursor/rules/frontend-angular.mdc" ] && \
   [ ! -L "${REPO}/.cursor/rules/frontend-angular.mdc" ]; then
  pass "legacy symlink replaced by a real file"
else
  fail "legacy symlink replaced by a real file"
fi

# --- pruning ----------------------------------------------------------------
printf -- '---\ndescription: gone\n---\n\n<!-- generated by second-brain-workflow@old from rules/gone.md -->\nstale\n' \
  > "${REPO}/.cursor/rules/gone.mdc"
render "${REPO}" >/dev/null 2>&1
assert_no_file "${REPO}/.cursor/rules/gone.mdc" "stale generated rule pruned"
assert_file "${REPO}/.cursor/rules/local-only.mdc" "hand-written rule never pruned"

# One target must not prune another agent's files, or a repo shared with a
# colleague on the other editor gets gutted.
render "${REPO}" --targets cursor >/dev/null 2>&1
assert_file "${REPO}/.claude/rules/frontend-angular.md" \
  "single target leaves the other agent's files alone"

# --- scoping invariant ------------------------------------------------------
BAD="${RULES_FIXTURES}/zz-test-bad.md"
printf -- '---\n---\n\n- no paths, no description\n' > "${BAD}"
render --explain >/dev/null 2>&1
rc=$?
rm -f "${BAD}"
assert_exit 1 "${rc}" "rule with neither paths nor description is rejected"

# --- config -----------------------------------------------------------------
printf 'RENDER_TARGETS=cursor\n' > "${SANDBOX}/config"
REPO2="${SANDBOX}/repo2"
make_target_repo "${REPO2}"
SBW_CONFIG_FILE="${SANDBOX}/config" render "${REPO2}" >/dev/null 2>&1
assert_file   "${REPO2}/.cursor/rules/frontend-angular.mdc" "config file sets RENDER_TARGETS"
assert_no_file "${REPO2}/.claude/rules"                     "config file narrows targets"

REPO3="${SANDBOX}/repo3"
make_target_repo "${REPO3}"
SBW_CONFIG_FILE="${SANDBOX}/config" RENDER_TARGETS=agents render "${REPO3}" >/dev/null 2>&1
assert_file    "${REPO3}/AGENTS.md"    "env overrides config file"
assert_no_file "${REPO3}/.cursor/rules/frontend-angular.mdc" "env override is exclusive"

# --- glob validity ----------------------------------------------------------
# A pattern that silently matches nothing is worse than a broken one: the rule
# just never fires. Both agents fail this way, so it is caught at render time.
BAD2="${RULES_FIXTURES}/zz-test-badglob.md"
printf -- '---\npaths:\n  - "photos [2024/**"\ndescription: bad glob\n---\n\n- oops\n' > "${BAD2}"
render --explain >/dev/null 2>&1
rc=$?
rm -f "${BAD2}"
assert_exit 1 "${rc}" "unbalanced bracket in a glob is rejected"

# A brace group is now legal in the canonical paths: list and only fails where
# Cursor's comma-separated globs cannot carry it.
BAD3="${RULES_FIXTURES}/zz-test-braces.md"
printf -- '---\npaths:\n  - "src/**/*.{ts,tsx}"\ndescription: braces\n---\n\n- ok\n' > "${BAD3}"
render --explain --targets cursor >/dev/null 2>&1
rc_cursor=$?
render --explain --targets claude-code >/dev/null 2>&1
rc_claude=$?
rm -f "${BAD3}"
assert_exit 1 "${rc_cursor}" "brace group rejected when cursor is a target"
assert_exit 0 "${rc_claude}" "brace group allowed when only claude-code is a target"

# --- the adopter's first five minutes ----------------------------------------
# A clone with no conventions yet must render what it can and say what is
# missing, not traceback. This is the cold-start path, not an error state.
AGENTS_FIXTURE="${FIXTURES}/AGENTS.md"
AGENTS_BAK="${SANDBOX}/AGENTS.md.bak"
cp "${AGENTS_FIXTURE}" "${AGENTS_BAK}"
rm -f "${AGENTS_FIXTURE}"
REPO4="${SANDBOX}/repo4"
make_target_repo "${REPO4}"
out="$(render "${REPO4}" 2>&1)"
rc=$?
cp "${AGENTS_BAK}" "${AGENTS_FIXTURE}"
assert_exit 0 "${rc}" "missing AGENTS.md does not fail the render"
assert_file   "${REPO4}/.claude/rules/frontend-angular.md" "rules still render without AGENTS.md"
assert_no_file "${REPO4}/AGENTS.md"                        "AGENTS.md not fabricated"
assert_no_file "${REPO4}/CLAUDE.md"                        "CLAUDE.md skipped without its import target"
TESTS_RUN=$((TESTS_RUN + 1))
if echo "${out}" | grep -q "AGENTS.md.example"; then
  pass "says how to fix it"
else
  fail "says how to fix it" "${out}"
fi

# --- engine version stamping -------------------------------------------------
# Own fixture repo, fully isolated from the idempotency/drift flow above.
V="$(cat "${ENGINE}/VERSION")"
REPO5="${SANDBOX}/repo5"
make_target_repo "${REPO5}"
render "${REPO5}" >/dev/null 2>&1

assert_contains "${REPO5}/.cursor/rules/frontend-angular.mdc" "(v${V})" \
  "rendered file carries the engine version"
assert_file "${REPO5}/.sbw-version" "writes .sbw-version"
assert_contains "${REPO5}/.sbw-version" "${V}" ".sbw-version carries the engine version"

echo "0.0.0-stale" > "${REPO5}/.sbw-version"
out="$(render "${REPO5}" --check 2>&1)"
rc=$?
assert_exit 1 "${rc}" "--check flags a stale .sbw-version as drift"
TESTS_RUN=$((TESTS_RUN + 1))
case "${out}" in
  *"DRIFT: .sbw-version"*) pass "names .sbw-version specifically" ;;
  *) fail "names .sbw-version specifically" "${out}" ;;
esac

render "${REPO5}" >/dev/null 2>&1
assert_contains "${REPO5}/.sbw-version" "${V}" "re-render fixes .sbw-version"

echo "0.0.0-stale" > "${REPO5}/.sbw-version"
render "${REPO5}" --dry-run >/dev/null 2>&1
assert_contains "${REPO5}/.sbw-version" "0.0.0-stale" "--dry-run does not touch .sbw-version"

# --- an always-on rule reaches AGENTS.md, and reaches it once ----------------
# AGENTS.md is the portable output — the one an editor this engine renders no
# native format for still reads. An always-on rule that landed in .cursor/rules
# and .claude/rules but not here meant one repo enforcing different rules
# depending on what you opened it in, with nothing saying so.
AO_RULES="${SANDBOX}/ao-rules/rules"
mkdir -p "${AO_RULES}"
cp "${RULES_FIXTURES}/frontend-angular.md" "${AO_RULES}/"
cp "${FIXTURES}/budget/rules/always-on.md" "${AO_RULES}/"
cp "${FIXTURES}/AGENTS.md" "${AO_RULES}/../AGENTS.md"
REPO_AO="${SANDBOX}/repo-ao"
make_target_repo "${REPO_AO}"
"${ENGINE}/scripts/render.py" --rules-dir "${AO_RULES}" "${REPO_AO}" >/dev/null 2>&1
assert_exit 0 $? "renders with an always-on rule present"
assert_contains "${REPO_AO}/AGENTS.md" "Fixture rule body" \
  "an always-on rule's body is appended to AGENTS.md"
assert_contains "${REPO_AO}/AGENTS.md" "always-on in every target" \
  "the appended section is headed by the rule's description"

# Once, not twice. Claude Code reads it through CLAUDE.md's @AGENTS.md import,
# so a per-rule file as well would load the same text twice and charge the
# budget for both.
assert_no_file "${REPO_AO}/.claude/rules/always-on.md" \
  "an always-on rule is not also emitted under .claude/rules"
assert_file "${REPO_AO}/.claude/rules/frontend-angular.md" \
  "a scoped rule still gets its own claude-code file"

# Cursor does not read AGENTS.md, so its always-on rules keep their own file.
assert_file "${REPO_AO}/.cursor/rules/always-on.mdc" \
  "cursor still gets an always-on rule as its own .mdc"
assert_contains "${REPO_AO}/.cursor/rules/always-on.mdc" "alwaysApply: true" \
  "the cursor always-on rule is marked alwaysApply"

# With no AGENTS.md there is nowhere to fold it into, so the per-rule file has
# to stay — dropping it would reintroduce the same silent gap from the other
# side.
NO_AO="${SANDBOX}/ao-noagents/rules"
mkdir -p "${NO_AO}"
cp "${FIXTURES}/budget/rules/always-on.md" "${NO_AO}/"
REPO_AO2="${SANDBOX}/repo-ao2"
make_target_repo "${REPO_AO2}"
"${ENGINE}/scripts/render.py" --rules-dir "${NO_AO}" "${REPO_AO2}" >/dev/null 2>&1
assert_file "${REPO_AO2}/.claude/rules/always-on.md" \
  "without AGENTS.md, an always-on rule falls back to its own claude-code file"
assert_no_file "${REPO_AO2}/AGENTS.md" "still no AGENTS.md fabricated"

# A hand-written AGENTS.md in the target is skipped by the writer, so folding
# the always-on rules into it drops them from every claude-code consumer. Found
# by re-rendering two real repos after v0.20.0: one took the fold, the other
# keeps its own AGENTS.md and received the rule nowhere at all.
REPO_AO3="${SANDBOX}/repo-ao3"
make_target_repo "${REPO_AO3}"
printf 'my own conventions, not yours\n' > "${REPO_AO3}/AGENTS.md"
"${ENGINE}/scripts/render.py" --rules-dir "${AO_RULES}" "${REPO_AO3}" >/dev/null 2>&1
assert_file "${REPO_AO3}/.claude/rules/always-on.md" \
  "a hand-written AGENTS.md keeps the always-on rule as its own file"
assert_contains "${REPO_AO3}/AGENTS.md" "my own conventions" \
  "a hand-written AGENTS.md is still never overwritten"


# --- --local: rendered here, invisible to the remote -------------------------
# The case this exists for: personal conventions in a repo owned by someone
# else. Rendering and committing are different decisions, and without this the
# second one happens by accident.
LOCAL_REPO="${SANDBOX}/local-repo"
make_target_repo "${LOCAL_REPO}"
"${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "${LOCAL_REPO}" --local >/dev/null 2>&1
assert_exit 0 $? "--local renders"
assert_file "${LOCAL_REPO}/.claude/rules/frontend-angular.md" "and writes the same files"
assert_file "${LOCAL_REPO}/.git/info/exclude" "and an exclude file exists"
assert_contains "${LOCAL_REPO}/.git/info/exclude" ".claude/rules/frontend-angular.md" \
  "naming each rendered file"
assert_contains "${LOCAL_REPO}/.git/info/exclude" ".sbw-version" \
  "including the version stamp, which is rendered output too"
# The claim the mode makes, checked against git rather than against the file we
# just wrote: an exclude entry that git disagrees with is worth nothing.
status="$(cd "${LOCAL_REPO}" && git status --porcelain --untracked-files=all)"
mine="$(printf '%s\n' "${status}" \
  | grep -c 'frontend-angular\|AGENTS.md\|CLAUDE.md\|sbw-version' || true)"
assert_str "0" "${mine}" "and git reports none of the files we rendered"
# The repo's *own* hand-written rule stays visible: --local hides what this
# engine wrote, never what was already there.
TESTS_RUN=$((TESTS_RUN + 1))
case "${status}" in
  *"local-only.mdc"*) pass "a hand-written rule in the repo is still git-visible" ;;
  *) fail "a hand-written rule in the repo is still git-visible" "${status}" ;;
esac

# Idempotent: a second run rewrites the block rather than appending a second.
"${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "${LOCAL_REPO}" --local >/dev/null 2>&1
headers="$(grep -c "second-brain-workflow: rendered locally" "${LOCAL_REPO}/.git/info/exclude" || true)"
assert_str "1" "${headers}" "a second --local run leaves one block, not two"

# --- a tracked file the render SKIPS is not worth refusing over --------------
# Reported from a work machine: --local refused because the repo tracked its own
# CLAUDE.md. But the writer skips a hand-written file, so it was never at risk of
# being shared — the check was asking "is it tracked" when the question is "would
# we write it". Refusing there blocks correct work over a file nothing touches.
TEAM_REPO="${SANDBOX}/team-owned"
make_target_repo "${TEAM_REPO}"
printf 'the teams own CLAUDE.md\n' > "${TEAM_REPO}/CLAUDE.md"
git -C "${TEAM_REPO}" add CLAUDE.md
git -C "${TEAM_REPO}" -c user.email=t@example.com -c user.name=T commit -qm "team file"
out="$("${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "${TEAM_REPO}" --local 2>&1)"
rc=$?
assert_exit 0 "${rc}" "--local proceeds when the tracked file is one the render skips"
TESTS_RUN=$((TESTS_RUN + 1))
case "${out}" in
  *"--local has nothing to hide"*"CLAUDE.md"*)
    pass "and names it as tracked-and-left-alone rather than refusing" ;;
  *) fail "and names it as tracked-and-left-alone rather than refusing" "${out}" ;;
esac
TESTS_RUN=$((TESTS_RUN + 1))
if grep -q '^CLAUDE.md$' "${TEAM_REPO}/.git/info/exclude"; then
  fail "a skipped file is not added to the exclude block" "CLAUDE.md was excluded"
else
  pass "a skipped file is not added to the exclude block"
fi
TESTS_RUN=$((TESTS_RUN + 1))
if [ "$(cat "${TEAM_REPO}/CLAUDE.md")" = "the teams own CLAUDE.md" ]; then
  pass "and the team's file is byte-identical afterwards"
else
  fail "and the team's file is byte-identical afterwards" "$(cat "${TEAM_REPO}/CLAUDE.md")"
fi

# ...but a tracked file the render *would* overwrite still refuses: that one is
# ours, already shared, and excluding it locally would hide a real modification.
OURS_REPO="${SANDBOX}/ours-tracked"
make_target_repo "${OURS_REPO}"
"${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "${OURS_REPO}" >/dev/null 2>&1
git -C "${OURS_REPO}" add AGENTS.md
git -C "${OURS_REPO}" -c user.email=t@example.com -c user.name=T commit -qm "committed ours"
out="$("${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "${OURS_REPO}" --local 2>&1)"
rc=$?
assert_exit 1 "${rc}" "a tracked file the render owns still refuses"
TESTS_RUN=$((TESTS_RUN + 1))
case "${out}" in
  *"cannot keep its promise"*"AGENTS.md"*) pass "naming it" ;;
  *) fail "naming it" "${out}" ;;
esac

# --- a hand-written AGENTS.md is skipped, not dropped from the plan ----------
# v0.20.1 joined two questions into one flag: whether a source AGENTS.md exists,
# and whether the target's is ours. Joined, a target with a hand-written
# AGENTS.md lost both AGENTS.md and CLAUDE.md from the plan entirely and warned
# that the *engine* had no AGENTS.md — false, and it hid the accurate skip line.
HANDWRITTEN="${SANDBOX}/handwritten-agents"
make_target_repo "${HANDWRITTEN}"
printf 'mine, not yours\n' > "${HANDWRITTEN}/AGENTS.md"
out="$("${ENGINE}/scripts/render.py" --rules-dir "${RULES_FIXTURES}" "${HANDWRITTEN}" 2>&1)"
TESTS_RUN=$((TESTS_RUN + 1))
case "${out}" in
  *"skip (hand-written, not ours): AGENTS.md"*)
    pass "a hand-written AGENTS.md is reported as skipped, by name" ;;
  *) fail "a hand-written AGENTS.md is reported as skipped, by name" "${out}" ;;
esac
TESTS_RUN=$((TESTS_RUN + 1))
case "${out}" in
  *"no AGENTS.md in"*) fail "and not reported as the engine having none" "${out}" ;;
  *) pass "and not reported as the engine having none" ;;
esac
assert_file "${HANDWRITTEN}/CLAUDE.md" "CLAUDE.md still renders alongside it"


finish
