"""Did this engine write this file?

One definition, because two consumers now ask the question for opposite reasons
and a drift between them is silent both ways.

`render.py` asks in order to decide what it may overwrite: a file carrying the
marker is ours and can be rewritten, one without it is the repo's and must not
be touched. That has been the rule since v0.46.

`lib/context_sources.py` asks in order to decide what *counts as evidence*.
Its tier 1 is "what the product is for, in the team's own words", and it lists
`CLAUDE.md` and `AGENTS.md` — which in an onboarded repo are frequently this
engine's own output (8 of the 31 agent files across this machine's registered
repos carry the marker). So onboarding a repo, or any later re-render, wrote a
tier-1 "product doc" and marked that repo's whole `context/` stale without a
single product fact changing. On 2026-09-22 `d427cbb` did exactly that to
`babypath-app`: three context files reported STALE, and the commit was
`chore: onboard the app into second-brain-workflow as shared`.

The fix is not to drop those filenames from the tier. **A hand-written
`AGENTS.md` is a genuine product doc** — it is often the clearest statement a
repo has of how its team works — and the engine deliberately refuses to
overwrite one. Name alone cannot separate the two; the marker can, and it is
the same question `render.py` already asks before writing.

Same shape as the v0.55.0 rule-budget defect: a correct computation over the
wrong input set.
"""

MARKER = "generated by second-brain-workflow@"

# The marker sits in a comment at the top of a rendered file. Reading a prefix
# rather than the whole file keeps this cheap enough to call per candidate in a
# survey that walks a repo.
_SCAN_BYTES = 2000

# The one line this engine writes *into* a file it does not own. When a repo
# keeps its own CLAUDE.md, render.py adds an `@AGENTS.md` import at the top so
# Claude Code reaches the shared standards; the rest of the file stays the
# repo's. So a hand-written product doc can carry an engine edit, and the
# marker cannot see it — the file is correctly unmarked.
IMPORT_LINE = "@AGENTS.md"


def is_generated(path):
    """True when `path` carries this engine's provenance marker.

    A path that cannot be read is **not** generated. That is the safe answer for
    both callers: `render.py` then declines to overwrite it, and a survey then
    keeps it as evidence — in each case the engine defers to the repo rather
    than claiming a file it could not open.
    """
    try:
        return MARKER in path.read_text(encoding="utf-8", errors="ignore")[:_SCAN_BYTES]
    except OSError:
        return False


def is_engine_line(line):
    """Is this one line of a diff something the engine wrote, rather than the team?

    Used to decide whether a *commit* moved the product. A render or an
    onboarding touches tier-1 files without saying anything about the product,
    and a consumer that treats it as movement reports a change nobody made.
    """
    body = line[1:].strip() if line[:1] in "+-" else line.strip()
    return not body or body == IMPORT_LINE or MARKER in body
