#!/usr/bin/env bash
# The set of repos this machine has rendered into. Source, don't execute.
#
#   . "$(dirname "$0")/lib/registry.sh"
#   sbw_registry_path                 # where the list lives
#   sbw_registry_read                 # one absolute path per line
#   sbw_registry_marker_present DIR   # does DIR still carry rendered output?
#
# Written by render.py (scripts/lib/registry.py) on a successful render, read
# here by doctor.sh. Why it exists at all is documented there; the short
# version is that nothing on the machine recorded where the engine had
# rendered, so "re-render everything after an upgrade" had to guess a glob —
# and a glob that matches nothing looks exactly like a machine that has
# onboarded nothing.
#
# Keep in step with lib/registry.py: same path, same format. Deliberately not
# the machine config file (that parser does not strip trailing comments, and
# this is a list, not key/value), and deliberately not redirected by
# SBW_CONFIG_FILE, which names the config file rather than a config directory.

sbw_registry_path() {
  local base="${XDG_CONFIG_HOME:-$HOME/.config}"
  echo "${base}/second-brain-workflow/repos"
}

# Blank lines and comments are stripped, so a hand-seeded file can be annotated.
sbw_registry_read() {
  local file line
  file="$(sbw_registry_path)"
  [ -f "${file}" ] || return 0
  while IFS= read -r line || [ -n "${line}" ]; do
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    case "${line}" in
      ''|'#'*) continue ;;
    esac
    printf '%s\n' "${line}"
  done < "${file}"
}

# Mirrors MARKER in scripts/render.py. tests/test-repo-registry.sh asserts the
# two strings are identical, so this copy cannot drift into never matching.
SBW_RENDER_MARKER="generated by second-brain-workflow@"

# Is this still a repo the engine rendered into? `.sbw-version` first: it is
# written on every successful render regardless of RENDER_TARGETS, so a
# cursor-only repo (no AGENTS.md, no CLAUDE.md) is not mistaken for a stale
# entry. The marker files are the fallback for a repo rendered by an engine old
# enough not to have written it.
sbw_registry_marker_present() {
  local repo="$1" f
  [ -f "${repo}/.sbw-version" ] && return 0
  for f in AGENTS.md CLAUDE.md; do
    [ -f "${repo}/${f}" ] || continue
    grep -qF "${SBW_RENDER_MARKER}" "${repo}/${f}" 2>/dev/null && return 0
  done
  return 1
}
