#!/usr/bin/env python3
"""Render one canonical rule set into each agent's native format.

Canonical source is `rules/*.md` plus `AGENTS.md`. Every target output is
generated — never edit a rendered file in a target repo, edit the source here
and re-render.

    render.py <target-repo> [--targets cursor,claude-code,agents]
              [--check] [--dry-run] [--explain] [--local | --shared]

Targets
    cursor       .cursor/rules/*.mdc      derived `globs` + `alwaysApply`
    claude-code  .claude/rules/*.md       `paths:` passed through, plus a
                                          root CLAUDE.md importing @AGENTS.md
    agents       AGENTS.md                portable, always-on

Source format is a YAML `paths:` list — Claude Code's native shape:

    ---
    paths:
      - "**/*.component.ts"
    description: Angular component conventions
    ---

A rule with `paths` is scoped; a rule without is always-on. There is no
`alwaysApply` field, because the contradictory state (scoped *and* always-on)
should not be expressible at all rather than caught by a check.

Cursor's `globs` is a comma-separated string, so it is the derived form, not
the source. That direction matters: a comma-separated field cannot carry a
brace group like `{ts,tsx}`, so making it canonical would forbid braces
everywhere. As the derived form, the limitation applies only when Cursor is a
target — see check_globs().

A successful render also appends the target's real path to the machine's repo
registry (see lib/registry.py) — the only thing this writes outside the target
repo, and the only record of where the engine has rendered. The render *mode*
(`local` or `shared`) is recorded there too, and an already-onboarded repo is
re-rendered in the mode it carries unless `--local` or `--shared` says otherwise:
`render.py <repo>` with no flag used to silently re-render a `--local` repo in
shared mode, which is how personal conventions end up committed to a shared
remote.

Stdlib only. Config: RENDER_TARGETS env var, or --targets. Rules location:
SBW_RULES_DIR env/config var, or --rules-dir — defaults to
ENGINE/rules, so a self-contained checkout (rules co-located with the
engine) needs no configuration at all.
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.config import load as load_config  # noqa: E402
from lib.registry import MODES as REGISTRY_MODES  # noqa: E402
from lib.registry import mode_of as recorded_mode  # noqa: E402
from lib.registry import read as registry_read  # noqa: E402
from lib.registry import register as register_repo  # noqa: E402
from lib.registry import registry_path as registry_file  # noqa: E402
from lib.repo_match import repo_files, path_matches  # noqa: E402

ENGINE = Path(__file__).resolve().parent.parent
RULES_SRC = ENGINE / "rules"
AGENTS_SRC = ENGINE / "AGENTS.md"
MARKER = "generated by second-brain-workflow@"
ALL_TARGETS = ("cursor", "claude-code", "agents")

# Files render.py owns in a target repo without the usual MARKER provenance
# comment, so the generic "no marker => hand-written, never touch" rule
# (is_generated(), used at both the write and prune call sites below) can't
# apply to them. Named here instead of a bare path string at the write site
# so a future change to that overwrite/prune logic has to notice this file
# rather than discover the exception by surprise. Deliberately NOT given a
# marker line even though nothing stops it (see the comment above the
# version-stamp block in main() for why): the point is to name the
# exception, not eliminate it.
HEADERLESS_OWNED = (".sbw-version",)


def repo_sha(path):
    try:
        return subprocess.run(
            ["git", "-C", str(path), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def repo_root(path):
    """None when path isn't inside a git repo at all (vs. a real repo root)."""
    try:
        return subprocess.run(
            ["git", "-C", str(path), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def engine_sha():
    return repo_sha(ENGINE)


def engine_version():
    """The engine's own release version, from VERSION at its repo root.

    Distinct from engine_sha()/content_sha in main(): a version is a stable,
    human-meaningful pin an adopter can clone at (`git checkout v0.1.0`); a
    sha is precise but says nothing about whether anything changed since the
    last release. Falls back rather than raising — an engine checkout that
    somehow lost VERSION should still render, just without a version stamp.
    """
    path = ENGINE / "VERSION"
    if path.is_file():
        return path.read_text(encoding="utf-8").strip()
    return "0.0.0-unversioned"


def unquote(value):
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def split_frontmatter(text):
    """Parse the leading `---` block. Handles scalars and a `paths:` block list."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    fm, key = {}, None
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.lstrip().startswith("- ") and key:
            fm.setdefault(key, [])
            if isinstance(fm[key], list):
                fm[key].append(unquote(line.lstrip()[2:].strip()))
            continue
        m = re.match(r"^([A-Za-z][\w-]*):(.*)$", line)
        if not m:
            continue
        key, value = m.group(1), m.group(2).strip()
        fm[key] = [] if value == "" else unquote(value)
    return fm, text[end + 4:].lstrip("\n")


def load_rules():
    rules = []
    for path in sorted(RULES_SRC.glob("*.md")):
        fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
        paths = fm.get("paths") or []
        if isinstance(paths, str):
            paths = [paths]
        rules.append(
            {
                "name": path.stem,
                "source": f"rules/{path.name}",
                "description": fm.get("description", ""),
                "globs": paths,
                # No `paths` means always-on — Claude Code's own semantics, so
                # the source needs no separate flag and cannot contradict itself.
                "always": not paths,
                "body": body.rstrip() + "\n",
            }
        )
    return rules


def scope_rules(rules, repo, scope):
    """The rules to render here. -> (rules, note) — note is "" under `all`.

    Under `all` every rule is written into every repo and the globs decide
    which ones *attach* at load time. That is safe and was never examined: on
    the machine this was written from it put 101 of 170 rendered files into
    repos where their globs cannot match anything — `app-flutter` in three Astro
    sites, `frontend-angular` in a Python API — so a rule that applies to one
    repo still had to be committed to ten.

    Under `relevant` a scoped rule is rendered only where one of its globs
    matches a file that is actually there. Always-on rules are unconditional:
    having no globs is a claim that they apply everywhere, and the absence of a
    matching file cannot contradict that.

    The set is a function of the repo's *current* files, which is the risk worth
    naming: a repo that later grows its first test file needs the test rule and
    will not have it. Nothing here papers over that — `--check` recomputes this
    same set, so the newly-matching rule shows up as a file that should exist
    and does not, which is drift and reported as such. That is why this may not
    be a write-time-only filter.

    Matching goes through lib/repo_match, the same code `skill_manifest relevant`
    and `practices-for` use, so "does this apply here" cannot get two answers on
    one repo depending on which command asked.
    """
    if scope != "relevant":
        return rules, ""

    # Our own output is not evidence about the repo. `rule-scoping` is scoped to
    # `**/.cursor/rules/*.mdc` and `**/.claude/rules/*.md`, so once a repo
    # commits what we rendered, that rule matches — because we put the files
    # there. It measured 10 of 10 repos on this machine for exactly that reason,
    # and every rule that renders more files would inherit the same circularity.
    #
    # A hand-written rule file still counts: those are the repo's own, and a rule
    # about writing path globs genuinely does apply where someone writes them.
    files = [f for f in repo_files(repo) if not is_generated(repo / f)]
    kept, dropped = [], []
    for r in rules:
        if r["always"] or any(path_matches(f, g) for g in r["globs"] for f in files):
            kept.append(r)
        else:
            dropped.append(r["name"])
    if not dropped:
        return kept, f"Scope:  relevant — all {len(kept)} rule(s) apply here"
    return kept, (
        f"Scope:  relevant — {len(kept)} of {len(rules)} rule(s) apply here; "
        f"not rendered: {', '.join(sorted(dropped))}"
    )


def check_globs(rules, targets):
    """Reject glob patterns an agent would silently treat as matching nothing.

    - `[` starts a bracket expression. A pattern with a `[` that cannot be read
      as one matches nothing (documented Claude Code behaviour). Always invalid.
    - A brace group containing a comma cannot survive Cursor's `globs`, which is
      one comma-separated string. This is now only an error when Cursor is a
      target: the canonical `paths:` list carries braces fine, and Claude Code
      expands them natively.
    """
    problems = []
    for r in rules:
        for g in r["globs"]:
            if g.count("[") != g.count("]"):
                problems.append(
                    f"{r['source']}: unbalanced '[' in glob {g!r} — matches nothing; "
                    "escape a literal bracket as \\["
                )
            if "cursor" in targets and re.search(r"\{[^}]*,[^}]*\}", g):
                problems.append(
                    f"{r['source']}: glob {g!r} has a brace group containing a comma, "
                    "which Cursor's comma-separated `globs` cannot represent. "
                    "Split it into separate paths entries, or drop cursor from "
                    "RENDER_TARGETS for this repo."
                )
    return problems


def check_scoping(rules):
    """Catch rules that would reach no agent at all.

    The old contradiction — scoped *and* always-on — is no longer expressible:
    `always` is derived from the absence of `paths`, so the two cannot both be
    true. That is the point of making `paths:` canonical rather than checking
    for a conflict between two independent fields.
    """
    problems = []
    for r in rules:
        if not r["globs"] and not r["description"]:
            problems.append(
                f"{r['source']}: no paths and no description — it would load "
                "unconditionally on Claude Code but be unreachable on Cursor. "
                "Add paths to scope it, or a description to make it findable."
            )
    return problems


def header(rel, sha):
    return (
        f"<!-- {MARKER}{sha} (v{engine_version()}) from {rel} — do not edit here; "
        f"edit {rel} at its source and re-render -->"
    )


def yaml_list(items):
    return "\n".join(f'  - "{i}"' for i in items)


def render_cursor(rule, sha):
    """Derived: a YAML paths list becomes one comma-separated `globs` string."""
    fm = [f"description: {rule['description']}"] if rule["description"] else []
    if rule["globs"]:
        fm.append('globs: "' + ", ".join(rule["globs"]) + '"')
    fm.append(f"alwaysApply: {'true' if rule['always'] else 'false'}")
    return (
        ".cursor/rules/%s.mdc" % rule["name"],
        "---\n" + "\n".join(fm) + "\n---\n\n"
        + header(rule["source"], sha) + "\n\n" + rule["body"],
    )


def render_claude_rule(rule, sha):
    """Near-identity: the canonical format *is* Claude Code's native shape.

    `paths:` passes through unchanged, and a rule without it loads
    unconditionally — no translation, so nothing to get wrong.
    """
    fm = []
    if rule["globs"]:
        fm.append("paths:\n" + yaml_list(rule["globs"]))
    if rule["description"]:
        fm.append(f"description: {rule['description']}")
    block = "---\n" + "\n".join(fm) + "\n---\n\n" if fm else ""
    return (
        ".claude/rules/%s.md" % rule["name"],
        block + header(rule["source"], sha) + "\n\n" + rule["body"],
    )


def render_agents(sha, always_on=()):
    """AGENTS.md carries the always-on rules, not only its hand-written body.

    It is the *portable* output — the one an editor this engine renders no native
    format for still reads. An always-on constraint that reached `.cursor/rules`
    and `.claude/rules` but not here meant one repo enforcing different rules
    depending on what you opened it in, with nothing anywhere saying so. A rule
    that constrains when work may be called done is exactly the kind that has to
    survive a tool switch.
    """
    body = AGENTS_SRC.read_text(encoding="utf-8").rstrip("\n")
    parts = [header("AGENTS.md", sha), "", body]
    for rule in always_on:
        parts += [
            "",
            header(rule["source"], sha),
            "",
            "## " + (rule["description"] or rule["name"]),
            "",
            rule["body"].strip("\n"),
        ]
    return "AGENTS.md", "\n".join(parts) + "\n"


def render_claude_md(sha):
    """Claude Code reads CLAUDE.md, not AGENTS.md — import it rather than fork it.

    The provenance comment is a block-level HTML comment, which Claude Code
    strips before loading, so it costs no context tokens.
    """
    return "CLAUDE.md", (
        header("AGENTS.md", sha) + "\n\n"
        "@AGENTS.md\n\n"
        "Path-scoped standards live in `.claude/rules/` and load when you touch\n"
        "matching files. Both are generated by second-brain-workflow — edit them there.\n"
    )


EXCLUDE_HEADER = "# second-brain-workflow: rendered locally, not shared"
EXCLUDE_FOOTER = "# end second-brain-workflow"


def git_dir(repo):
    """The repo's real .git directory, or None if this is not a work tree.

    `git rev-parse` rather than `repo / ".git"`: in a worktree or a submodule
    that path is a *file* pointing elsewhere, and writing an exclude file beside
    it would put it where nothing reads.
    """
    import subprocess
    try:
        out = subprocess.run(["git", "-C", str(repo), "rev-parse", "--absolute-git-dir"],
                             capture_output=True, text=True, check=False)
    except OSError:
        return None
    return Path(out.stdout.strip()) if out.returncode == 0 and out.stdout.strip() else None


def tracked_paths(repo, rels):
    """Which of `rels` git already tracks here.

    The whole point of --local is that the team never sees these files, and
    `.git/info/exclude` has no effect on a path already in the index — it would
    show up as a plain modification, one `git commit -a` from being shared. So
    this is checked before anything is written, and it refuses rather than
    warns: a mode that cannot keep its promise should not half-keep it.
    """
    import subprocess
    if not rels:
        return []
    out = subprocess.run(["git", "-C", str(repo), "ls-files", "--"] + list(rels),
                         capture_output=True, text=True, check=False)
    if out.returncode != 0:
        return []
    return sorted(line for line in out.stdout.splitlines() if line.strip())


def write_exclude(repo, rels):
    """Add the rendered paths to .git/info/exclude, inside a marked block.

    Rewritten whole each run rather than appended to, so re-rendering after a
    rule is added or a target changes cannot leave a stale half-list behind, and
    a second run is not a second copy.

    An empty `rels` removes the block instead of writing an empty one — that is
    `--shared` switching a repo back, and a header with nothing under it would
    read to the next `exclude_block_present()` as a repo still in local mode.
    """
    gd = git_dir(repo)
    if gd is None:
        return None
    info = gd / "info"
    info.mkdir(parents=True, exist_ok=True)
    path = info / "exclude"
    existing = path.read_text(encoding="utf-8") if path.exists() else ""

    kept, skipping = [], False
    for line in existing.splitlines():
        if line.strip() == EXCLUDE_HEADER:
            skipping = True
            continue
        if skipping:
            if line.strip() == EXCLUDE_FOOTER:
                skipping = False
            continue
        kept.append(line)

    block = [EXCLUDE_HEADER] + sorted(set(rels)) + [EXCLUDE_FOOTER] if rels else []
    lines = [l for l in kept if l.strip() or kept.index(l) < len(kept) - 1] + block
    text = ("\n".join(lines) + "\n") if lines else ""
    path.write_text(text, encoding="utf-8")
    return path


def exclude_block_present(repo):
    """Does this clone already carry our .git/info/exclude block?

    The fallback for a registry line written before the mode field existed. It
    is inference rather than a declaration — grepping another repo's git
    internals is a reasonable recovery, not a source of truth — which is exactly
    why the answer is recorded on the first render that learns it.
    """
    gd = git_dir(repo)
    if gd is None:
        return False
    try:
        return EXCLUDE_HEADER in (gd / "info" / "exclude").read_text(
            encoding="utf-8", errors="ignore")
    except OSError:
        return False


def resolve_mode(repo, asked, reporting):
    """Which mode this render uses: ("local"|"shared", note-for-the-reader).

    `asked` is "local", "shared", or None when no flag was given. The default is
    not "shared" — it is *preserve*. `render.py <repo>` on a repo onboarded with
    --local re-rendered it in shared mode: the existing exclude block survived,
    but rules added since onboarding landed outside it and showed up untracked,
    and in a repo where those paths are tracked (or after a `git add -A`) that is
    personal conventions committed to a shared remote. Nothing warned, and the
    command that walked into it is the `fix:` line `make upgrade` prints.

    Ambiguity refuses rather than guesses, the same shape as the vault id: a
    recorded value this engine does not understand is not resolved to a default,
    because the default decides who sees your conventions.
    """
    recorded = recorded_mode(repo)
    if recorded is not None and recorded not in REGISTRY_MODES and not asked:
        # Only when no flag was given: an explicit --local/--shared *is* the
        # answer, and refusing then would leave no way to repair the line.
        sys.exit(
            f"The repo registry records mode={recorded!r} for {repo}, which this "
            f"engine does not understand (known: {', '.join(REGISTRY_MODES)}).\n"
            "Refusing rather than picking one: the mode decides whether this "
            "repo's remote sees the rendered files.\n"
            "Pass --local or --shared to state it, or fix the line in "
            f"{registry_file()}."
        )
    if recorded not in REGISTRY_MODES:
        recorded = None

    registered = os.path.realpath(str(repo)) in registry_read()
    inferred = source = None
    if recorded is None:
        if exclude_block_present(repo):
            inferred, source = "local", "inferred from .git/info/exclude"
        elif registered:
            # Registered, no mode field, no exclude block: rendered before the
            # field existed and not rendered locally. That is `shared`, and
            # recording it is what makes the gap self-healing.
            inferred = "shared"
            source = "inferred: registered, with no local-exclusion block"
    known = recorded or inferred
    if recorded:
        source = "recorded"

    if asked:
        if known and asked != known:
            return asked, (f"Mode: {asked} — switching this repo from {known} "
                           f"({source}), because --{asked} says so.")
        return asked, f"Mode: {asked}"
    if known:
        if known == "local":
            return known, (
                "Mode: local (%s) — kept from how this repo was onboarded, so\n"
                "        the rendered files stay out of its remote. --shared to change it."
                % source)
        return known, f"Mode: shared ({source})"
    # Nothing to preserve: a first render, where the flags are the whole answer.
    return "shared", "Mode: shared (first render here)" if not reporting else "Mode: shared"


def would_write(repo, rel):
    """Would a render actually write this path, or does it skip it?

    The tracked-path refusal must ask this, not merely "is it tracked". A
    hand-written file already in the repo is *skipped* by the writer — the team's
    own CLAUDE.md is never modified — so refusing over it would refuse over a
    file at no risk of being shared, which is the check being wrong in the
    direction that blocks correct work.
    """
    dest = repo / rel
    if rel in HEADERLESS_OWNED:
        return True                     # overwritten unconditionally
    if dest.is_symlink():
        return True                     # legacy link, always replaced
    if dest.exists() and not is_generated(dest):
        return False                    # hand-written: the writer skips it
    return True


def agents_is_writable(repo):
    """Will this repo's AGENTS.md actually be written by us?

    Absent (we create it) or carrying our marker (we own it) — but a
    hand-written AGENTS.md is skipped by the writer, and folding the always-on
    rules into a file that is never written drops them entirely. This has to be
    a fact about the *target*, not about the engine, because that is where the
    answer differs: one onboarded repo took the fold correctly and the other
    keeps its own AGENTS.md and would have lost the rule.
    """
    path = repo / "AGENTS.md"
    return not path.exists() or is_generated(path)


def plan(rules, targets, sha, warn=None, fold_always_on=True):
    """-> {relative path: content} for every configured target.

    AGENTS.md is optional. A fresh engine with no conventions yet should render
    its rules and say what is missing, not traceback — that state is an
    adopter's first five minutes, not an error.
    """
    out = {}
    always_on = [r for r in rules if r["always"]]
    # Whether AGENTS.md can carry the always-on set decides where it is emitted
    # for Claude Code. With no AGENTS.md there is nowhere to fold it into, so the
    # per-rule files stay — dropping them would be the silent gap this change
    # exists to close, reintroduced from the other side.
    # Two conditions, and both are necessary. There has to be a source AGENTS.md
    # to append to, *and* the target repo has to be one whose AGENTS.md we
    # actually write — a hand-written one is skipped, and folding into a file
    # that is never written drops the rule from every claude-code consumer.
    # Two different questions, conflated in v0.20.1 and separated here. Whether
    # there is a source AGENTS.md to render decides if AGENTS.md and CLAUDE.md
    # are planned at all; whether the *target's* AGENTS.md is ours decides only
    # whether always-on rules fold into it. Joined, a target with a hand-written
    # AGENTS.md dropped both files from the plan and warned that the *engine* had
    # no AGENTS.md — false, and it hid the accurate "skip (hand-written, not
    # ours)" the writer would otherwise have printed.
    have_agents = AGENTS_SRC.is_file()
    fold_here = have_agents and fold_always_on
    if "cursor" in targets:
        # Cursor does not read AGENTS.md, so its always-on rules keep their own
        # files with alwaysApply: true. Nothing to fold, nothing duplicated.
        for r in rules:
            p, c = render_cursor(r, sha)
            out[p] = c
    if "claude-code" in targets:
        for r in rules:
            if r["always"] and fold_here:
                # Reaches Claude Code through CLAUDE.md's @AGENTS.md import.
                # Emitting it here as well would load the same text twice and
                # count it twice against the budget.
                continue
            p, c = render_claude_rule(r, sha)
            out[p] = c
    if "agents" in targets or "claude-code" in targets:
        if have_agents:
            p, c = render_agents(sha, always_on if fold_here else ())
            out[p] = c
            if "claude-code" in targets:
                p, c = render_claude_md(sha)
                out[p] = c
        elif warn:
            warn(
                f"no {AGENTS_SRC.name} in {ENGINE} — skipping AGENTS.md and "
                "CLAUDE.md. Copy AGENTS.md.example to AGENTS.md to add "
                "always-on conventions."
            )
    return out


def owned_dirs(targets):
    dirs = []
    if "cursor" in targets:
        dirs.append((".cursor/rules", ".mdc"))
    if "claude-code" in targets:
        dirs.append((".claude/rules", ".md"))
    return dirs


def is_generated(path):
    try:
        return MARKER in path.read_text(encoding="utf-8", errors="ignore")[:2000]
    except OSError:
        return False


def strip_marker(text):
    return "\n".join(l for l in text.splitlines() if MARKER not in l)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("target_repo", nargs="?", help="repo to render into")
    ap.add_argument("--targets", help="override RENDER_TARGETS for this run")
    ap.add_argument("--scope", choices=("all", "relevant"),
                    help="override SBW_RENDER_SCOPE for this run")
    ap.add_argument("--rules-dir", help="override SBW_RULES_DIR for this run")
    ap.add_argument("--check", action="store_true", help="exit 1 on drift, write nothing")
    ap.add_argument("--dry-run", action="store_true", help="print planned actions")
    # Mutually exclusive: "local and shared" is not a state, so it is refused
    # by the parser rather than resolved by precedence further down.
    modes = ap.add_mutually_exclusive_group()
    modes.add_argument("--local", action="store_true",
                       help="also exclude the rendered files locally, so the repo's "
                            "remote never sees them")
    modes.add_argument("--shared", action="store_true",
                       help="render normally, and stop excluding the files locally "
                            "— the explicit way to move a --local repo back")
    ap.add_argument("--no-register", action="store_true",
                    help="render without recording the repo as onboarded "
                         "(throwaway fixtures, probes)")
    ap.add_argument("--explain", action="store_true", help="print resolution and exit")
    args = ap.parse_args()

    cfg = load_config(warn=lambda m: print(f"warning: {m}", file=sys.stderr))
    targets_raw = args.targets or cfg["RENDER_TARGETS"]
    targets = [t.strip() for t in targets_raw.split(",") if t.strip()]
    scope = args.scope or cfg["SBW_RENDER_SCOPE"]
    if scope not in ("all", "relevant"):
        sys.exit(
            f"SBW_RENDER_SCOPE is {scope!r}; expected 'all' or 'relevant'. "
            "Refusing rather than picking one, since the two render different "
            "file sets and the wrong guess would delete rules from a repo."
        )
    unknown = [t for t in targets if t not in ALL_TARGETS]
    if unknown:
        sys.exit(f"Unknown target(s): {', '.join(unknown)}. Known: {', '.join(ALL_TARGETS)}")

    # Rules may live outside the engine checkout entirely (a separate,
    # private repo). Defaulting to ENGINE/rules keeps a self-contained
    # checkout working with zero configuration.
    global RULES_SRC, AGENTS_SRC
    rules_dir_override = args.rules_dir or cfg["SBW_RULES_DIR"]
    RULES_SRC = Path(rules_dir_override).expanduser().resolve() if rules_dir_override else ENGINE / "rules"
    AGENTS_SRC = RULES_SRC.parent / "AGENTS.md"

    rules = load_rules()
    if not rules:
        print(f"No rules found in {RULES_SRC} — nothing to render.")
        return 0

    problems = check_scoping(rules) + check_globs(rules, targets)
    for p in problems:
        print(f"error: {p}", file=sys.stderr)
    if problems:
        return 1

    # The sha stamped into rendered file headers should identify the repo
    # that actually owns rules/AGENTS.md content — the engine repo when
    # co-located (unchanged behavior), a separate rules repo when split out.
    engine_root = repo_root(ENGINE)
    rules_root = repo_root(RULES_SRC)
    split = bool(rules_root) and rules_root != engine_root
    sha = engine_sha()
    content_sha = repo_sha(RULES_SRC) if split else sha

    if args.explain:
        print(f"engine {ENGINE} @ {sha} (v{engine_version()})")
        if split:
            print(f"rules  {RULES_SRC.parent} @ {content_sha}")
        print(f"targets: {', '.join(targets)}\n")
        for r in rules:
            scope = "always-on" if r["always"] else (
                "scoped: " + ", ".join(r["globs"]) if r["globs"] else "description-matched"
            )
            print(f"{r['name']}  [{scope}]")
            print(f"  source: {r['source']}")
            for t in targets:
                for path in plan([r], [t], content_sha):
                    if path not in ("AGENTS.md", "CLAUDE.md"):
                        print(f"  {t}: {path}")
            print()
        print("always-on files:")
        if "agents" in targets or "claude-code" in targets:
            print("  AGENTS.md")
        if "claude-code" in targets:
            print("  CLAUDE.md (imports @AGENTS.md)")
        return 0

    if not args.target_repo:
        ap.error("target_repo is required unless --explain is given")
    repo = Path(args.target_repo).expanduser().resolve()
    if not repo.is_dir():
        sys.exit(f"Target repo not found: {repo}")

    reporting = args.check or args.dry_run
    asked = "local" if args.local else ("shared" if args.shared else None)
    share_mode, mode_note = resolve_mode(repo, asked, reporting)
    local = share_mode == "local"

    if local and not reporting and git_dir(repo) is None:
        # Refuses whether the mode was asked for or preserved. A repo recorded
        # local that is no longer a work tree is precisely the ambiguous state
        # this must not resolve by rendering it shared.
        sys.exit(f"{'--local' if asked else 'local mode'} needs a git work tree: "
                 f"{repo} is not one. There is nothing to keep out of a remote "
                 "here." + ("" if asked else "\nThe registry records this repo as "
                            "local. Pass --shared if that is no longer true."))

    rules, scope_note = scope_rules(rules, repo, scope)
    if scope_note:
        print(scope_note)

    fold = agents_is_writable(repo)
    rendered = plan(rules, targets, content_sha,
                    warn=lambda m: print(f"warning: {m}", file=sys.stderr),
                    fold_always_on=fold)
    if not fold and any(r["always"] for r in rules) and "claude-code" in targets:
        print("note: AGENTS.md here is hand-written, so the always-on rules stay "
              "as their own files under .claude/rules/ rather than being folded "
              "into it.", file=sys.stderr)
    if local:
        planned = sorted(list(rendered) + list(HEADERLESS_OWNED))
        tracked = tracked_paths(repo, planned)
        already = [p for p in tracked if would_write(repo, p)]
        skipped = [p for p in tracked if p not in already]
        if skipped:
            # Named, not refused over: these stay exactly as the repo has them.
            print("note: git tracks these and the render leaves them alone, so "
                  "local mode has nothing to hide:", file=sys.stderr)
            for rel in skipped:
                print(f"        {rel}", file=sys.stderr)
        if already:
            sys.exit(
                "local mode cannot keep its promise here: git already tracks\n"
                + "".join(f"  {p}\n" for p in already)
                + ".git/info/exclude has no effect on a tracked path — it would show\n"
                  "up as an ordinary modification, one `git commit -a` from being\n"
                  "shared. Nothing was written.\n\n"
                  "Either render without --local and decide file by file, or agree\n"
                  "the rules with whoever owns this repo."
            )

    mode = "check" if args.check else ("dry-run" if args.dry_run else "write")
    print(f"Engine: {ENGINE} @ {sha} (v{engine_version()})")
    if split:
        print(f"Rules:  {RULES_SRC.parent} @ {content_sha}")
    print(f"Target: {repo}  [{mode}] -> {', '.join(targets)}")
    # Said every run, whichever mode it is. Who sees your conventions is a
    # decision worth restating rather than a default worth forgetting, and it is
    # also the line that shows a preserved mode was preserved.
    print(f"  {mode_note}")

    drift = changed = stamp_behind = 0

    for rel, content in sorted(rendered.items()):
        dest = repo / rel
        # A symlink is left over from the pre-copy layout — always ours, always
        # replaced. Reading through it would find no marker and misclassify it
        # as hand-written.
        legacy_link = dest.is_symlink()
        if legacy_link and mode == "write":
            dest.unlink()
        if not legacy_link and dest.exists() and not is_generated(dest):
            print(f"  skip (hand-written, not ours): {rel}")
            if rel == "CLAUDE.md":
                print("     add `@AGENTS.md` at its top to pick up shared standards")
            continue
        if legacy_link and mode != "write":
            print(f"  {'DRIFT' if mode == 'check' else 'would replace'}: {rel} (legacy symlink)")
            drift = 1
            continue
        if dest.exists() and strip_marker(dest.read_text(encoding="utf-8")) == strip_marker(content):
            continue
        if mode == "check":
            print(f"  DRIFT: {rel}")
            drift = 1
        elif mode == "dry-run":
            print(f"  would write: {rel}")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
            print(f"  wrote: {rel}")
            changed += 1

    # A simple stamp of which engine version last rendered here — nothing in
    # the target repo carried this before, so this is the one new file this
    # writes outside .cursor/rules, .claude/rules, AGENTS.md and CLAUDE.md.
    # Treated like any other rendered file for --check/--dry-run reporting
    # (drift is visible as "the engine moved on and this repo hasn't
    # re-rendered since"), but NOT run through is_generated()'s hand-written
    # check like the rest of `rendered` below: unlike a rule or CLAUDE.md, a
    # human has no legitimate reason to hand-edit this file, and adding a
    # marker line to make it eligible for that check would misclassify every
    # already-rendered repo's existing (pre-marker) .sbw-version as
    # hand-written on first contact with this code — silently freezing its
    # drift detection forever instead of fixing it. Unconditional overwrite,
    # named via HEADERLESS_OWNED above, is the intentional choice here.
    (version_name,) = HEADERLESS_OWNED
    version_content = engine_version() + "\n"
    version_dest = repo / version_name
    if not version_dest.exists() or version_dest.read_text(encoding="utf-8") != version_content:
        if mode == "check":
            # Deliberately NOT drift. This file holds a bare engine version, so
            # it differs after every release — including the ones that changed
            # nothing about what this repo renders. Counting it as drift meant
            # cutting a release marked every onboarded repo on the machine as
            # behind, and "behind" is the word that sends someone to re-render
            # and commit a one-line change in ten repos. Twice in one day here.
            #
            # The question `--check` exists to answer is whether this repo's
            # agents load the rules as they stand. Identical content answers
            # yes, whatever the stamp says. The stamp is provenance, it catches
            # up on the next render that has a reason of its own, and a real
            # format change moves the content too — so nothing is lost by
            # letting it lag.
            # No claim about content on this line — it is printed before the
            # rule files have all been compared, and the summary below is where
            # "current" is either true or replaced by "Drift detected".
            print(f"  stamp behind: {version_name}")
            stamp_behind = 1
        elif mode == "dry-run":
            print(f"  would write: {version_name}")
        else:
            version_dest.write_text(version_content, encoding="utf-8")
            print(f"  wrote: {version_name}")
            changed += 1

    # Prune per target, so a repo rendered for one agent does not accumulate
    # stale files for another. Only our own generated files are ever removed.
    for subdir, ext in owned_dirs(targets):
        d = repo / subdir
        if not d.is_dir():
            continue
        for existing in sorted(d.glob(f"*{ext}")):
            rel = str(existing.relative_to(repo))
            if rel in rendered or not is_generated(existing):
                continue
            if mode == "check":
                print(f"  DRIFT: stale generated file {rel}")
                drift = 1
            elif mode == "dry-run":
                print(f"  would prune: {rel}")
            else:
                existing.unlink()
                print(f"  pruned: {rel}")
                changed += 1

    # Recorded after the writes, and only in write mode: --check and --dry-run
    # change nothing anywhere, which is the same contract .sbw-version already
    # has and what tests/test-render.sh already asserts for it. A repo that
    # rendered fine is still rendered when this fails, so the failure warns
    # rather than propagating — but it does warn, because an unwritable
    # registry is exactly how the onboarded set becomes undetermined later with
    # nothing left to explain it.
    # `--no-register` is for a render into something that is not a repo you
    # onboarded: a throwaway fixture, a probe, a scratch checkout. Without it,
    # verify-claude-load.sh — which renders into a mktemp directory and deletes
    # it seconds later — added a permanent registry line per run, and the
    # author's registry accumulated four dead entries in one day: three probes
    # and one canary fixture. doctor then reports each of them forever, since
    # it deliberately never prunes (an unmounted volume is not a deleted repo),
    # so the noise is not self-clearing and it is indistinguishable from the
    # finding that matters.
    #
    # A flag rather than "skip anything under $TMPDIR": the registry records
    # intent, and intent is the caller's to state. Sniffing the path would be a
    # guess about what a directory means, in a file whose whole value is that
    # its entries were put there deliberately.
    if mode == "write" and not args.no_register:
        # The mode travels with the path. A line written before this field
        # existed gains it here, from the exclude-block inference above — which
        # is what makes the gap self-healing rather than a migration.
        register_repo(repo, mode=share_mode,
                      warn=lambda m: print(f"warning: {m}", file=sys.stderr))

    if mode == "write" and local:
        # Only what this render owns. A hand-written file the writer skipped is
        # the repo's, and listing it here would be a no-op entry implying we are
        # hiding something we never wrote.
        rels = sorted(p for p in list(rendered) + list(HEADERLESS_OWNED)
                      if would_write(repo, p))
        written = write_exclude(repo, rels)
        print()
        print(f"Excluded locally in {written}:")
        for rel in rels:
            print(f"  {rel}")
        # Said every run, not only the first. The whole point of the mode is a
        # decision about who sees these rules, and a decision that stops being
        # restated is one that quietly becomes a default.
        print("These files exist here and this repo's remote will never see them.")
        print("Nothing about the exclusion is committed either — .git/info/exclude")
        print("is local to this clone, so a fresh clone elsewhere has neither.")
    elif mode == "write" and args.shared and exclude_block_present(repo):
        # --shared is the explicit switch back, so it finishes the job: leaving
        # the block behind would keep hiding the files it names while the
        # registry says they are shared, and the next reader would have two
        # sources disagreeing about the same repo.
        written = write_exclude(repo, [])
        print()
        print(f"Removed the local-exclusion block from {written}.")
        print("This repo's rendered files are now ordinary untracked files —")
        print("`git status` will show them, and committing them shares them.")

    if mode == "check":
        if drift:
            print("Drift detected.")
            return 1
        if stamp_behind:
            # Exit 0: repos-check and upgrade both branch on this code, and both
            # ask "is this repo behind the rules as they stand". It is not.
            print("Clean — no drift. The version stamp lags a newer engine and")
            print("will be rewritten by the next render that has its own reason.")
            return 0
        print("Clean — no drift.")
    elif mode == "dry-run":
        print("Dry run — nothing written.")
    else:
        print(f"Rendered {changed} file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
