#!/usr/bin/env python3
"""Render one canonical rule set into each agent's native format.

Canonical source is `rules/*.md` plus `AGENTS.md`. Every target output is
generated — never edit a rendered file in a target repo, edit the source here
and re-render.

    render.py <target-repo> [--targets cursor,claude-code,agents]
              [--check] [--dry-run] [--explain]

Targets
    cursor       .cursor/rules/*.mdc      derived `globs` + `alwaysApply`
    claude-code  .claude/rules/*.md       `paths:` passed through, plus a
                                          root CLAUDE.md importing @AGENTS.md
    agents       AGENTS.md                portable, always-on

Source format is a YAML `paths:` list — Claude Code's native shape:

    ---
    paths:
      - "**/*.component.ts"
    description: Angular component conventions
    ---

A rule with `paths` is scoped; a rule without is always-on. There is no
`alwaysApply` field, because the contradictory state (scoped *and* always-on)
should not be expressible at all rather than caught by a check.

Cursor's `globs` is a comma-separated string, so it is the derived form, not
the source. That direction matters: a comma-separated field cannot carry a
brace group like `{ts,tsx}`, so making it canonical would forbid braces
everywhere. As the derived form, the limitation applies only when Cursor is a
target — see check_globs().

Stdlib only. Config: RENDER_TARGETS env var, or --targets. Rules location:
SBW_RULES_DIR env/config var, or --rules-dir — defaults to
ENGINE/rules, so a self-contained checkout (rules co-located with the
engine) needs no configuration at all.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.config import load as load_config  # noqa: E402

ENGINE = Path(__file__).resolve().parent.parent
RULES_SRC = ENGINE / "rules"
AGENTS_SRC = ENGINE / "AGENTS.md"
MARKER = "generated by second-brain-workflow@"
ALL_TARGETS = ("cursor", "claude-code", "agents")


def repo_sha(path):
    try:
        return subprocess.run(
            ["git", "-C", str(path), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def repo_root(path):
    """None when path isn't inside a git repo at all (vs. a real repo root)."""
    try:
        return subprocess.run(
            ["git", "-C", str(path), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def engine_sha():
    return repo_sha(ENGINE)


def unquote(value):
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def split_frontmatter(text):
    """Parse the leading `---` block. Handles scalars and a `paths:` block list."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    fm, key = {}, None
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.lstrip().startswith("- ") and key:
            fm.setdefault(key, [])
            if isinstance(fm[key], list):
                fm[key].append(unquote(line.lstrip()[2:].strip()))
            continue
        m = re.match(r"^([A-Za-z][\w-]*):(.*)$", line)
        if not m:
            continue
        key, value = m.group(1), m.group(2).strip()
        fm[key] = [] if value == "" else unquote(value)
    return fm, text[end + 4:].lstrip("\n")


def load_rules():
    rules = []
    for path in sorted(RULES_SRC.glob("*.md")):
        fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
        paths = fm.get("paths") or []
        if isinstance(paths, str):
            paths = [paths]
        rules.append(
            {
                "name": path.stem,
                "source": f"rules/{path.name}",
                "description": fm.get("description", ""),
                "globs": paths,
                # No `paths` means always-on — Claude Code's own semantics, so
                # the source needs no separate flag and cannot contradict itself.
                "always": not paths,
                "body": body.rstrip() + "\n",
            }
        )
    return rules


def check_globs(rules, targets):
    """Reject glob patterns an agent would silently treat as matching nothing.

    - `[` starts a bracket expression. A pattern with a `[` that cannot be read
      as one matches nothing (documented Claude Code behaviour). Always invalid.
    - A brace group containing a comma cannot survive Cursor's `globs`, which is
      one comma-separated string. This is now only an error when Cursor is a
      target: the canonical `paths:` list carries braces fine, and Claude Code
      expands them natively.
    """
    problems = []
    for r in rules:
        for g in r["globs"]:
            if g.count("[") != g.count("]"):
                problems.append(
                    f"{r['source']}: unbalanced '[' in glob {g!r} — matches nothing; "
                    "escape a literal bracket as \\["
                )
            if "cursor" in targets and re.search(r"\{[^}]*,[^}]*\}", g):
                problems.append(
                    f"{r['source']}: glob {g!r} has a brace group containing a comma, "
                    "which Cursor's comma-separated `globs` cannot represent. "
                    "Split it into separate paths entries, or drop cursor from "
                    "RENDER_TARGETS for this repo."
                )
    return problems


def check_scoping(rules):
    """Catch rules that would reach no agent at all.

    The old contradiction — scoped *and* always-on — is no longer expressible:
    `always` is derived from the absence of `paths`, so the two cannot both be
    true. That is the point of making `paths:` canonical rather than checking
    for a conflict between two independent fields.
    """
    problems = []
    for r in rules:
        if not r["globs"] and not r["description"]:
            problems.append(
                f"{r['source']}: no paths and no description — it would load "
                "unconditionally on Claude Code but be unreachable on Cursor. "
                "Add paths to scope it, or a description to make it findable."
            )
    return problems


def header(rel, sha):
    return (
        f"<!-- {MARKER}{sha} from {rel} — do not edit here; "
        f"edit {rel} at its source and re-render -->"
    )


def yaml_list(items):
    return "\n".join(f'  - "{i}"' for i in items)


def render_cursor(rule, sha):
    """Derived: a YAML paths list becomes one comma-separated `globs` string."""
    fm = [f"description: {rule['description']}"] if rule["description"] else []
    if rule["globs"]:
        fm.append('globs: "' + ", ".join(rule["globs"]) + '"')
    fm.append(f"alwaysApply: {'true' if rule['always'] else 'false'}")
    return (
        ".cursor/rules/%s.mdc" % rule["name"],
        "---\n" + "\n".join(fm) + "\n---\n\n"
        + header(rule["source"], sha) + "\n\n" + rule["body"],
    )


def render_claude_rule(rule, sha):
    """Near-identity: the canonical format *is* Claude Code's native shape.

    `paths:` passes through unchanged, and a rule without it loads
    unconditionally — no translation, so nothing to get wrong.
    """
    fm = []
    if rule["globs"]:
        fm.append("paths:\n" + yaml_list(rule["globs"]))
    if rule["description"]:
        fm.append(f"description: {rule['description']}")
    block = "---\n" + "\n".join(fm) + "\n---\n\n" if fm else ""
    return (
        ".claude/rules/%s.md" % rule["name"],
        block + header(rule["source"], sha) + "\n\n" + rule["body"],
    )


def render_agents(sha):
    body = AGENTS_SRC.read_text(encoding="utf-8")
    return "AGENTS.md", header("AGENTS.md", sha) + "\n\n" + body


def render_claude_md(sha):
    """Claude Code reads CLAUDE.md, not AGENTS.md — import it rather than fork it.

    The provenance comment is a block-level HTML comment, which Claude Code
    strips before loading, so it costs no context tokens.
    """
    return "CLAUDE.md", (
        header("AGENTS.md", sha) + "\n\n"
        "@AGENTS.md\n\n"
        "Path-scoped standards live in `.claude/rules/` and load when you touch\n"
        "matching files. Both are generated by second-brain-workflow — edit them there.\n"
    )


def plan(rules, targets, sha, warn=None):
    """-> {relative path: content} for every configured target.

    AGENTS.md is optional. A fresh engine with no conventions yet should render
    its rules and say what is missing, not traceback — that state is an
    adopter's first five minutes, not an error.
    """
    out = {}
    if "cursor" in targets:
        for r in rules:
            p, c = render_cursor(r, sha)
            out[p] = c
    if "claude-code" in targets:
        for r in rules:
            p, c = render_claude_rule(r, sha)
            out[p] = c
    if "agents" in targets or "claude-code" in targets:
        if AGENTS_SRC.is_file():
            p, c = render_agents(sha)
            out[p] = c
            if "claude-code" in targets:
                p, c = render_claude_md(sha)
                out[p] = c
        elif warn:
            warn(
                f"no {AGENTS_SRC.name} in {ENGINE} — skipping AGENTS.md and "
                "CLAUDE.md. Copy AGENTS.md.example to AGENTS.md to add "
                "always-on conventions."
            )
    return out


def owned_dirs(targets):
    dirs = []
    if "cursor" in targets:
        dirs.append((".cursor/rules", ".mdc"))
    if "claude-code" in targets:
        dirs.append((".claude/rules", ".md"))
    return dirs


def is_generated(path):
    try:
        return MARKER in path.read_text(encoding="utf-8", errors="ignore")[:2000]
    except OSError:
        return False


def strip_marker(text):
    return "\n".join(l for l in text.splitlines() if MARKER not in l)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("target_repo", nargs="?", help="repo to render into")
    ap.add_argument("--targets", help="override RENDER_TARGETS for this run")
    ap.add_argument("--rules-dir", help="override SBW_RULES_DIR for this run")
    ap.add_argument("--check", action="store_true", help="exit 1 on drift, write nothing")
    ap.add_argument("--dry-run", action="store_true", help="print planned actions")
    ap.add_argument("--explain", action="store_true", help="print resolution and exit")
    args = ap.parse_args()

    cfg = load_config(warn=lambda m: print(f"warning: {m}", file=sys.stderr))
    targets_raw = args.targets or cfg["RENDER_TARGETS"]
    targets = [t.strip() for t in targets_raw.split(",") if t.strip()]
    unknown = [t for t in targets if t not in ALL_TARGETS]
    if unknown:
        sys.exit(f"Unknown target(s): {', '.join(unknown)}. Known: {', '.join(ALL_TARGETS)}")

    # Rules may live outside the engine checkout entirely (a separate,
    # private repo). Defaulting to ENGINE/rules keeps a self-contained
    # checkout working with zero configuration.
    global RULES_SRC, AGENTS_SRC
    rules_dir_override = args.rules_dir or cfg["SBW_RULES_DIR"]
    RULES_SRC = Path(rules_dir_override).expanduser().resolve() if rules_dir_override else ENGINE / "rules"
    AGENTS_SRC = RULES_SRC.parent / "AGENTS.md"

    rules = load_rules()
    if not rules:
        print(f"No rules found in {RULES_SRC} — nothing to render.")
        return 0

    problems = check_scoping(rules) + check_globs(rules, targets)
    for p in problems:
        print(f"error: {p}", file=sys.stderr)
    if problems:
        return 1

    # The sha stamped into rendered file headers should identify the repo
    # that actually owns rules/AGENTS.md content — the engine repo when
    # co-located (unchanged behavior), a separate rules repo when split out.
    engine_root = repo_root(ENGINE)
    rules_root = repo_root(RULES_SRC)
    split = bool(rules_root) and rules_root != engine_root
    sha = engine_sha()
    content_sha = repo_sha(RULES_SRC) if split else sha

    if args.explain:
        print(f"engine {ENGINE} @ {sha}")
        if split:
            print(f"rules  {RULES_SRC.parent} @ {content_sha}")
        print(f"targets: {', '.join(targets)}\n")
        for r in rules:
            scope = "always-on" if r["always"] else (
                "scoped: " + ", ".join(r["globs"]) if r["globs"] else "description-matched"
            )
            print(f"{r['name']}  [{scope}]")
            print(f"  source: {r['source']}")
            for t in targets:
                for path in plan([r], [t], content_sha):
                    if path not in ("AGENTS.md", "CLAUDE.md"):
                        print(f"  {t}: {path}")
            print()
        print("always-on files:")
        if "agents" in targets or "claude-code" in targets:
            print("  AGENTS.md")
        if "claude-code" in targets:
            print("  CLAUDE.md (imports @AGENTS.md)")
        return 0

    if not args.target_repo:
        ap.error("target_repo is required unless --explain is given")
    repo = Path(args.target_repo).expanduser().resolve()
    if not repo.is_dir():
        sys.exit(f"Target repo not found: {repo}")

    rendered = plan(rules, targets, content_sha,
                    warn=lambda m: print(f"warning: {m}", file=sys.stderr))
    mode = "check" if args.check else ("dry-run" if args.dry_run else "write")
    print(f"Engine: {ENGINE} @ {sha}")
    if split:
        print(f"Rules:  {RULES_SRC.parent} @ {content_sha}")
    print(f"Target: {repo}  [{mode}] -> {', '.join(targets)}")

    drift = changed = 0

    for rel, content in sorted(rendered.items()):
        dest = repo / rel
        # A symlink is left over from the pre-copy layout — always ours, always
        # replaced. Reading through it would find no marker and misclassify it
        # as hand-written.
        legacy_link = dest.is_symlink()
        if legacy_link and mode == "write":
            dest.unlink()
        if not legacy_link and dest.exists() and not is_generated(dest):
            print(f"  skip (hand-written, not ours): {rel}")
            if rel == "CLAUDE.md":
                print("     add `@AGENTS.md` at its top to pick up shared standards")
            continue
        if legacy_link and mode != "write":
            print(f"  {'DRIFT' if mode == 'check' else 'would replace'}: {rel} (legacy symlink)")
            drift = 1
            continue
        if dest.exists() and strip_marker(dest.read_text(encoding="utf-8")) == strip_marker(content):
            continue
        if mode == "check":
            print(f"  DRIFT: {rel}")
            drift = 1
        elif mode == "dry-run":
            print(f"  would write: {rel}")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
            print(f"  wrote: {rel}")
            changed += 1

    # Prune per target, so a repo rendered for one agent does not accumulate
    # stale files for another. Only our own generated files are ever removed.
    for subdir, ext in owned_dirs(targets):
        d = repo / subdir
        if not d.is_dir():
            continue
        for existing in sorted(d.glob(f"*{ext}")):
            rel = str(existing.relative_to(repo))
            if rel in rendered or not is_generated(existing):
                continue
            if mode == "check":
                print(f"  DRIFT: stale generated file {rel}")
                drift = 1
            elif mode == "dry-run":
                print(f"  would prune: {rel}")
            else:
                existing.unlink()
                print(f"  pruned: {rel}")
                changed += 1

    if mode == "check":
        if drift:
            print("Drift detected.")
            return 1
        print("Clean — no drift.")
    elif mode == "dry-run":
        print("Dry run — nothing written.")
    else:
        print(f"Rendered {changed} file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
